### ISSUE TITLE
Reprint request～

### ISSUE THREAD

**Issue by DeeRenjie** [llama-development/PlayerSync#1]
Dear author：
　　Can I reprint your excellent plug-in to China's largest "minecraft" forum mcbbs? Thank you very much, because many server owners like this plug-in, so I have made your introduction Chinese.

**Comment by ProxmaDev** [comment]
Sure, but please include these two links:
Nukkit: https://nukkitx.com/resources/playersync.367/
GitHub: https://github.com/llama-development/PlayerSync

Best regards & stay healthy,
Proxma

**Comment by DeeRenjie** [comment]
Thank you very much, dear author
I've already sent it ~
PlayerSync —— 可以跨多个服务器同步玩家数据［全版本］
https://www.mcbbs.net/thread-1042911-1-1.html
